[package]
name = "starflet-protocol"
version = "0.1.0"
authors = ["Delightlabs"]
edition = "2018"
description = "Common helpers for starflet-protocol"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8.0" } 
cosmwasm-std = { version = "0.16.0", default-features = false, features = ["iterator"] }
cosmwasm-storage = { version = "0.16.0", default-features = false, features = ["iterator"] }
terraswap = { version = "2.4.0" }
terra-cosmwasm = { version = "2.2.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cosmwasm-bignumber = "2.2.0"
strum = "0.23"
strum_macros = "0.23"
protobuf = { version = "2", features = ["with-bytes"] }

[profile.release]
overflow-checks = true